# Generated by Django 4.1.6 on 2023-03-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('NORMAL', 'NORMAL'), ('LOW', 'LOW'), ('HIGH', 'HIGH')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('ASSIGNED-DEV', 'ASSIGNED-DEV'), ('REVIEW-NEEDED', 'REVIEW-NEEDED'), ('RESOLVED-DEV', 'RESOLVED-DEV'), ('TESTING-NEEDED', 'TESTING-NEEDED'), ('CLOSED', 'CLOSED')], default='NEW', max_length=30)),
                ('time', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('BACKEND', 'BACKEND'), ('ANDROID', 'ANDROID')], max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='main.ticket')),
            ],
        ),
    ]
