# Generated by Django 4.0.6 on 2022-07-31 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('NORMAL', 'NORMAL'), ('LOW', 'LOW'), ('HIGH', 'HIGH')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('ASSIGNED-DEV', 'ASSIGNED-DEV'), ('REVIEW-NEEDED', 'REVIEW-NEEDED'), ('RESOLVED-DEV', 'RESOLVED-DEV')], default='NEW', max_length=30)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
