# Generated by Django 4.1.6 on 2023-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='backlog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='version',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
