# Generated by Django 3.2.3 on 2022-08-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('ASSIGNED-DEV', 'ASSIGNED-DEV'), ('REVIEW-NEEDED', 'REVIEW-NEEDED'), ('RESOLVED-DEV', 'RESOLVED-DEV'), ('CLOSED', 'CLOSED')], default='NEW', max_length=30),
        ),
    ]
