# Generated by Django 3.2.3 on 2022-08-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220821_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
    ]
